import chokidar from 'chokidar';
import fs from 'fs';
import path from 'path';

interface ActionMetadata {
	filePath: string; // Relative path to workspace file
	importPath: string; // Calculated target runtime file import
	actionNamespace: string; // Complete period separated accessor name: example.sayHello
	methodName: string; // Camel-cased isolated final method execution label
	folders: string[]; // Array of containing target directory hierarchies
	payloadType: string;
	returnType: string;
}

export async function generateCommand(options: { watch: boolean }) {
	const cwd = process.cwd();
	const configPath = path.join(cwd, 'fan.config.json');

	if (!fs.existsSync(configPath)) {
		console.error('❌ Config File "fan.config.json" missing. Execute `fan init` first.');
		process.exit(1);
	}

	const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
	const actionsFolder = path.join(cwd, 'src/fan/actions');

	const executeGeneration = () => {
		try {
			console.log('🔨 Scanning action maps and rebuilding generation artifacts...');
			const actions = findActionsRecursively(actionsFolder, actionsFolder);

			generateBackendRouter(cwd, actions);
			generateFrontendBundle(cwd, config.angularServicePath, actions);
			console.log('✨ Generation complete.');
		} catch (err) {
			console.error('❌ Generation Error:', err);
		}
	};

	executeGeneration();

	if (options.watch) {
		console.log(`👀 Watching active codebase under ${actionsFolder} for changes...`);
		const watcher = chokidar.watch('**/*.action.ts', { cwd: actionsFolder, ignoreInitial: true });
		watcher.on('all', () => {
			executeGeneration();
		});
	}
}

function findActionsRecursively(
	baseDir: string,
	currentDir: string,
	accumulatedFolders: string[] = [],
): ActionMetadata[] {
	let results: ActionMetadata[] = [];
	if (!fs.existsSync(currentDir)) return results;

	const files = fs.readdirSync(currentDir);

	for (const file of files) {
		const fullPath = path.join(currentDir, file);
		const stat = fs.statSync(fullPath);

		if (stat.isDirectory()) {
			const camelFolder = toCamelCase(file);
			results = results.concat(
				findActionsRecursively(baseDir, fullPath, [...accumulatedFolders, camelFolder]),
			);
		} else if (file.endsWith('.action.ts')) {
			const actionName = toCamelCase(file.split('.action.ts')[0]);
			const fullNamespace = [...accumulatedFolders, actionName].join('.');

			// Compute relative import resolution for the backend generator routing tree
			let relativeImport = path.relative(path.join(baseDir, '..'), fullPath).replace(/\\/g, '/');
			if (!relativeImport.startsWith('.')) relativeImport = './' + relativeImport;
			relativeImport = relativeImport.replace(/\.ts$/, '');

			// Extract standard type parameters from file signature
			const contents = fs.readFileSync(fullPath, 'utf8');
			const typeSignature = parseSignatures(contents);

			results.push({
				filePath: fullPath,
				importPath: relativeImport,
				actionNamespace: fullNamespace,
				methodName: actionName,
				folders: accumulatedFolders,
				payloadType: typeSignature.payload,
				returnType: typeSignature.response,
			});
		}
	}
	return results;
}

function parseSignatures(content: string): { payload: string; response: string } {
	// Look for export const action = async (payload: Type, ...): Promise<Type>
	const regex =
		/export\s+const\s+action\s*=\s*async\s*\(\s*payload\s*:\s*([^,)]+)[^]*?\)\s*:\s*Promise\s*<\s*([^>]+)\s*>/gim;
	const match = regex.exec(content);
	if (match) {
		return { payload: match[1].trim(), response: match[2].trim() };
	}
	return { payload: 'any', response: 'any' };
}

function toCamelCase(str: string): string {
	return str.replace(/[-_]([a-z])/g, (g) => g[1].toUpperCase()).replace(/[-_]/g, '');
}

/**
 * Writes Backend Mapping Dispatcher File
 */
function generateBackendRouter(cwd: string, actions: ActionMetadata[]) {
	const lines: string[] = [
		`// =================================================================`,
		`// ⚠️ AUTO GENERATED BY FANSTACK. DO NOT MODIFY THIS FILE MANUALLY.`,
		`// =================================================================`,
		`import { HttpsError } from 'firebase-functions/v2/https';`,
		`import { ActionContext } from './action-context';`,
	];

	actions.forEach((act, idx) => {
		lines.push(`import { action as a${idx} } from '${act.importPath}';`);
	});

	lines.push(
		`\nexport const runAction = async (actionName: string, payload: any, context: ActionContext): Promise<any> => {`,
	);

	actions.forEach((act, idx) => {
		lines.push(`  ${idx === 0 ? '' : 'else '}if (actionName === '${act.actionNamespace}') {`);
		lines.push(`    return await a${idx}(payload, context);`);
		lines.push(`  }`);
	});

	lines.push(
		`  else {`,
		`    throw new HttpsError('not-found', \`Action "\${actionName}" not found.\`);`,
		`  }`,
		`};`,
	);

	fs.writeFileSync(path.join(cwd, 'src/fan/fan-actions.gen.ts'), lines.join('\n'), 'utf8');
}

/**
 * Builds Unified Frontend Client File
 */
function generateFrontendBundle(
	cwd: string,
	relativeAngularPath: string,
	actions: ActionMetadata[],
) {
	const angularTargetFile = path.resolve(cwd, relativeAngularPath, 'fan-func-service.gen.ts');

	// 1. Gather interface extractions
	const interfacesDir = path.join(cwd, 'src/fan/interfaces');
	let concatenatedInterfaces = '';
	if (fs.existsSync(interfacesDir)) {
		const files = fs.readdirSync(interfacesDir);
		for (const file of files) {
			if (file.endsWith('.ts')) {
				const content = fs.readFileSync(path.join(interfacesDir, file), 'utf8');
				// Strip out external file import statements
				const stripped = content.replace(/^import\s+[\s\S]*?(?:;|$)/gim, '');
				concatenatedInterfaces += `\n// Interfaces from ${file}\n${stripped}\n`;
			}
		}
	}

	// 2. Load custom base content directly
	const baseClassPath = path.join(cwd, 'src/fan/templates/func-service-base.ts');
	const baseClassContent = fs.existsSync(baseClassPath)
		? fs.readFileSync(baseClassPath, 'utf8').replace(/import\s+[^;]+;/gim, '')
		: '';

	// 3. Render nested tree architecture layout strings for the service properties
	const treeLines = buildClientTreeStructure(actions);

	const serviceCode = [
		`import { Injectable, inject } from '@angular/core';`,
		`import { Functions, httpsCallable } from '@angular/fire/functions';`,
		`import { firstValueFrom } from 'rxjs';`,
		`\n// =================================================================`,
		`// ⚠️ AUTO GENERATED BY FANSTACK. DO NOT MODIFY THIS FILE MANUALLY.`,
		`// =================================================================`,
		concatenatedInterfaces,
		`\n// Base Client Runner Class Definition`,
		baseClassContent,
		`\n@Injectable({ providedIn: 'root' })`,
		`export class FuncService extends FuncServiceBase {`,
		treeLines,
		`}`,
	].join('\n');

	// Ensure destination target paths are created fully before stream injection
	fs.mkdirSync(path.dirname(angularTargetFile), { recursive: true });
	fs.writeFileSync(angularTargetFile, serviceCode, 'utf8');
}

function buildClientTreeStructure(actions: ActionMetadata[]): string {
	const root: any = { actions: [], children: {} };

	for (const action of actions) {
		let current = root;
		for (const folder of action.folders) {
			if (!current.children[folder]) {
				current.children[folder] = { actions: [], children: {} };
			}
			current = current.children[folder];
		}
		current.actions.push(action);
	}

	function renderNode(node: any, indent: string, isRoot: boolean): string {
		let output = '';

		// Render direct actions belonging to this deep leaf namespace
		for (const act of node.actions) {
			const isNoPayload = ['void', 'null', 'undefined'].includes(act.payloadType.trim());
			if (isNoPayload) {
				output += `${indent}${act.methodName}: this._callNoPayload<${act.returnType}>('${act.actionNamespace}'),\n`;
			} else {
				output += `${indent}${act.methodName}: this._call<${act.payloadType}, ${act.returnType}>('${act.actionNamespace}'),\n`;
			}
		}

		// Render namespaces
		for (const childName of Object.keys(node.children)) {
			if (isRoot) {
				output += `${indent}public ${childName} = {\n`;
				output += renderNode(node.children[childName], indent + '\t', false);
				output += `${indent}};\n`;
			} else {
				output += `${indent}${childName}: {\n`;
				output += renderNode(node.children[childName], indent + '\t', false);
				output += `${indent}},\n`;
			}
		}

		return output;
	}

	return renderNode(root, '\t', true);
}
